package rules

import (
	"reflect"
	"strings"
	"testing"

	"github.com/yasyf/slop-cop/internal/detectors"
	"github.com/yasyf/slop-cop/internal/types"
)

func TestRuleCounts(t *testing.T) {
	if len(Slop) != 48 {
		t.Errorf("len(Slop) = %d, want 48", len(Slop))
	}
	if len(Base) != 9 {
		t.Errorf("len(Base) = %d, want 9", len(Base))
	}
	if len(Google) != 169 {
		t.Errorf("len(Google) = %d, want 169", len(Google))
	}
	if len(All) != 226 {
		t.Errorf("len(All) = %d, want 226", len(All))
	}
}

// Slop-first ordering is load-bearing: the LLM prompt numbers rules by
// position, so appending Base and then Google must leave the numbering of
// every earlier layer alone.
func TestAllIsSlopThenBaseThenGoogle(t *testing.T) {
	if !reflect.DeepEqual(All[:len(Slop)], Slop) {
		t.Fatal("All does not open with Slop in order")
	}
	if !reflect.DeepEqual(All[len(Slop):len(Slop)+len(Base)], Base) {
		t.Fatal("Base does not follow Slop in order")
	}
	if !reflect.DeepEqual(All[len(Slop)+len(Base):], Google) {
		t.Fatal("All does not close with Google in order")
	}
}

func TestRuleIDsUnique(t *testing.T) {
	seen := make(map[string]bool, len(All))
	for _, r := range All {
		if seen[r.ID] {
			t.Errorf("duplicate rule ID %q", r.ID)
		}
		seen[r.ID] = true
	}
}

func TestBaseRecordsComplete(t *testing.T) {
	for _, r := range Base {
		t.Run(r.ID, func(t *testing.T) {
			if r.Category != types.CategoryBase {
				t.Errorf("category = %q, want %q", r.Category, types.CategoryBase)
			}
			for name, field := range map[string]string{
				"Name":         r.Name,
				"Description":  r.Description,
				"Tip":          r.Tip,
				"Color":        r.Color,
				"BgColor":      r.BgColor,
				"RewriteHint":  r.RewriteHint,
				"LLMDirective": r.LLMDirective,
			} {
				if strings.TrimSpace(field) == "" {
					t.Errorf("%s is empty", name)
				}
			}
			if r.RequiresLLM != (r.LLMDetectionHint != "") {
				t.Errorf("RequiresLLM = %v but LLMDetectionHint present = %v",
					r.RequiresLLM, r.LLMDetectionHint != "")
			}
			if r.RequiresLLM != (r.LLMTier != "") {
				t.Errorf("RequiresLLM = %v but LLMTier = %q", r.RequiresLLM, r.LLMTier)
			}
		})
	}
}

func TestBaseColorsAreDistinct(t *testing.T) {
	slop := map[string]bool{}
	for _, r := range Slop {
		slop[r.Color] = true
	}
	used := map[string]bool{}
	for _, r := range Base {
		if slop[r.Color] {
			t.Errorf("%s reuses slop-layer colour %s", r.ID, r.Color)
		}
		if used[r.Color] {
			t.Errorf("%s reuses base-layer colour %s", r.ID, r.Color)
		}
		used[r.Color] = true
	}
}

// The tier counts are over rules that actually run an LLM pass. Note the
// upstream quirk pinned by TestFalseRangeCarriesAStrayTier.
func TestLLMTierCounts(t *testing.T) {
	sentence, document := 0, 0
	for _, r := range All {
		if !r.RequiresLLM {
			continue
		}
		switch r.LLMTier {
		case types.LLMTierSentence:
			sentence++
		case types.LLMTierDocument:
			document++
		default:
			t.Errorf("%s requires an LLM but names no tier", r.ID)
		}
	}
	if sentence != 40 {
		t.Errorf("sentence-tier rules = %d, want 40", sentence)
	}
	if document != 8 {
		t.Errorf("document-tier rules = %d, want 8", document)
	}
}

// false-range carries a sentence tier while running client-side. That is
// upstream data inside the provenance boundary, so it is pinned here rather
// than fixed — a tier count that ignores RequiresLLM reads 12, not 11.
func TestFalseRangeCarriesAStrayTier(t *testing.T) {
	r, ok := ByID["false-range"]
	if !ok {
		t.Fatal("false-range is missing from ByID")
	}
	if r.RequiresLLM || r.LLMTier != types.LLMTierSentence {
		t.Fatalf("false-range = {RequiresLLM:%v LLMTier:%q}, want {false sentence}", r.RequiresLLM, r.LLMTier)
	}
}

func TestByIDResolvesEveryRule(t *testing.T) {
	for _, r := range All {
		got, ok := ByID[r.ID]
		if !ok {
			t.Errorf("%s is missing from ByID", r.ID)
			continue
		}
		if got.Name != r.Name {
			t.Errorf("ByID[%q] resolves to %q", r.ID, got.Name)
		}
	}
}

// kitchenSink trips all eight client-side base detectors.
const kitchenSink = `The pipeline reads the source file from disk and then hands the bytes to the ` +
	`analyzer, which masks every span that is not prose, and after that the detectors run in ` +
	`order over the masked copy and each one emits its own violations for the report.

One runs. Two runs. Three runs. Four runs. Five runs. Six runs. Seven runs.

The report is generated by the analyzer.

The flag allows you to skip the check.

The command line tool prints JSON.

There is a flag that controls the layer.

The script makes use of the cache.

The change is not uncommon.`

// Every rule ID the base layer can emit must resolve in ByID, or check.go
// silently drops the violation when it looks the rule up for rendering.
func TestRunBaseEmitsOnlyKnownRules(t *testing.T) {
	got := detectors.RunBase(kitchenSink)
	if len(got) == 0 {
		t.Fatal("the kitchen-sink fixture tripped no detector")
	}
	seen := map[string]bool{}
	for _, v := range got {
		if _, ok := ByID[v.RuleID]; !ok {
			t.Errorf("RunBase emitted %q, which resolves in no rule", v.RuleID)
		}
		seen[v.RuleID] = true
	}
	for _, id := range []string{
		"long-sentence", "long-paragraph", "passive-voice", "padded-verb",
		"missing-hyphen", "expletive-opener", "nominalization",
	} {
		if !seen[id] {
			t.Errorf("the fixture did not trip %s", id)
		}
	}
	// DetectPlainWord extends the vocabulary of the slop layer's
	// elevated-register rule rather than adding a base-layer one, so the ID it
	// emits resolves in Slop.
	if !seen["elevated-register"] {
		t.Error("the fixture did not trip elevated-register")
	}
	if _, ok := byID(Base, "elevated-register"); ok {
		t.Error("elevated-register belongs to the slop layer, not Base")
	}
	if _, ok := byID(Slop, "elevated-register"); !ok {
		t.Error("elevated-register is missing from Slop")
	}
}

func byID(list []types.ViolationRule, id string) (types.ViolationRule, bool) {
	for _, r := range list {
		if r.ID == id {
			return r, true
		}
	}
	return types.ViolationRule{}, false
}
