// Package rules contains the full rule set ported 1:1 from
// https://github.com/awnist/slop-cop/blob/main/src/rules.ts.
package rules

import "github.com/yasyf/slop-cop/internal/types"

// All is the canonical ordered list of rules.
var All = []types.ViolationRule{
	// ── Word Choice ──────────────────────────────────────────────────────────
	{
		ID:           "overused-intensifiers",
		Name:         "Overused Intensifier",
		Category:     types.CategoryWordChoice,
		Description:  `Words like "crucial," "vital," "robust," "leverage," "delve," etc. are LLM clichés that add noise.`,
		Tip:          `Delete it. If the sentence still makes sense, the word was never needed. If it doesn't, rewrite the sentence to show why it matters.`,
		CanRemove:    true,
		Color:        "#f59e0b",
		BgColor:      "rgba(245,158,11,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Remove overused intensifiers like "crucial", "vital", "robust", "leverage", "delve", "nuanced", "unprecedented" — delete them or restructure the sentence.`,
		LLMDirective: `Remove the flagged overused intensifiers — delete them or rephrase the sentence without them.`,
	},
	{
		ID:           "elevated-register",
		Name:         "Elevated Register",
		Category:     types.CategoryWordChoice,
		Description:  `Using "utilize" instead of "use," "commence" instead of "start," "facilitate" instead of "help."`,
		Tip:          `Replace with the simpler word. "Utilize" → "use." "Commence" → "start." Elevated register performs intelligence rather than demonstrating it.`,
		CanRemove:    false,
		Color:        "#f97316",
		BgColor:      "rgba(249,115,22,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Replace elevated vocabulary with simpler words: utilize→use, commence→start, facilitate→help, endeavor→try, demonstrate→show, craft→write/make.`,
		LLMDirective: `Replace elevated register with plain equivalents: 'utilize'→'use', 'commence'→'start', 'facilitate'→'help', 'endeavor'→'try', 'demonstrate'→'show'.`,
	},
	{
		ID:           "filler-adverbs",
		Name:         "Filler Adverb",
		Category:     types.CategoryWordChoice,
		Description:  `"Importantly," "essentially," "fundamentally," "ultimately," "inherently" signal importance without substantiating it.`,
		Tip:          `Remove it. If the sentence still works, the adverb was empty. If it doesn't work without it, the sentence needs to be rewritten to earn the emphasis.`,
		CanRemove:    true,
		Color:        "#eab308",
		BgColor:      "rgba(234,179,8,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Delete sentence-opening filler adverbs: importantly, essentially, fundamentally, ultimately, inherently.`,
		LLMDirective: `Do not open sentences with filler adverbs (importantly, essentially, fundamentally, ultimately, inherently).`,
	},
	{
		ID:           "almost-hedge",
		Name:         `"Almost" Hedge`,
		Category:     types.CategoryWordChoice,
		Description:  `"Almost always," "almost never," "almost certainly" — hedging instead of committing to the pattern.`,
		Tip:          `Commit. "Almost always" → "usually." Or just say "always" and defend the claim. Readers notice when you won't take a stance.`,
		CanRemove:    false,
		Color:        "#84cc16",
		BgColor:      "rgba(132,204,22,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Replace "almost always/never/certainly" with a direct claim or a precise qualifier like "usually" or "rarely".`,
		LLMDirective: `Do not hedge with 'almost always', 'almost never', 'almost certainly' — commit to the claim directly.`,
	},
	{
		ID:           "era-opener",
		Name:         `"In an Era of…"`,
		Category:     types.CategoryWordChoice,
		Description:  `Opening phrase that stalls before reaching the actual argument.`,
		Tip:          `Delete this clause entirely and start the sentence at the real point. "In an era of rapid change, companies must adapt" → "Companies must adapt."`,
		CanRemove:    false,
		Color:        "#22d3ee",
		BgColor:      "rgba(34,211,238,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Delete era-opener clauses ("In an era of...", "In a world where...") and start at the real point.`,
		LLMDirective: `Do not open with era-framing clauses ('In an era of...', 'In a world where...') — start at the real point.`,
	},

	// ── Framing ──────────────────────────────────────────────────────────────
	{
		ID:           "metaphor-crutch",
		Name:         "Metaphor Crutch",
		Category:     types.CategoryFraming,
		Description:  `Predictable metaphors: "double-edged sword," "tip of the iceberg," "north star," "game-changer," etc.`,
		Tip:          `Either find a specific, original image from the actual subject matter, or drop the metaphor and say the thing plainly.`,
		CanRemove:    false,
		Color:        "#a78bfa",
		BgColor:      "rgba(167,139,250,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Replace clichéd metaphors (double-edged sword, north star, game-changer, deep dive) with plain language or a specific concrete image.`,
		LLMDirective: `Replace the flagged clichéd metaphors with plain language or a specific concrete image.`,
	},
	{
		ID:           "broader-implications",
		Name:         `"Broader Implications"`,
		Category:     types.CategoryFraming,
		Description:  `Zooming out to claim significance without substantiation.`,
		Tip:          `State the implication explicitly, or cut the phrase. "This has broader implications" says nothing. What are the implications? Say them.`,
		CanRemove:    false,
		Color:        "#38bdf8",
		BgColor:      "rgba(56,189,248,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Replace "broader/wider implications" with the actual specific implication, or delete the phrase.`,
		LLMDirective: `Do not use 'broader implications' or 'wider implications' — state the actual implication or delete the phrase.`,
	},

	// ── Sentence Structure ───────────────────────────────────────────────────
	{
		ID:           "em-dash-pivot",
		Name:         "Em-Dash Overuse",
		Category:     types.CategorySentenceStructure,
		Description:  `Em-dashes used as catch-all punctuation instead of choosing the right mark.`,
		Tip:          `Ask what relationship this dash is expressing. A pause → comma. A list → colon. A parenthetical → parentheses. A new sentence → period. Choose the right tool.`,
		CanRemove:    false,
		Color:        "#fb7185",
		BgColor:      "rgba(251,113,133,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Replace em-dashes with appropriate punctuation: comma for a pause, colon for elaboration, parentheses for an aside, period for a new sentence.`,
		LLMDirective: `Do not use em-dashes (—). Replace each with the correct punctuation: comma for a pause, colon for elaboration, parentheses for an aside, period for a new sentence.`,
	},
	{
		ID:           "negation-pivot",
		Name:         "Negation Pivot",
		Category:     types.CategorySentenceStructure,
		Description:  `"Not X, but Y" / "don't X, but Y" — negation followed by reframe. A hallmark LLM rhetorical structure.`,
		Tip:          `Rewrite as a direct positive claim. "We don't constrain through prohibition, but through amplification" → "We constrain through amplification." Lead with what is true, not what isn't.`,
		CanRemove:    false,
		Color:        "#f43f5e",
		BgColor:      "rgba(244,63,94,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Rewrite "not X, but Y" constructions as direct positive claims. Lead with what is true, not what isn't.`,
		LLMDirective: `Do not use 'not X, but Y' constructions — rewrite as a direct positive claim.`,
	},
	{
		ID:           "colon-elaboration",
		Name:         "Colon Elaboration",
		Category:     types.CategorySentenceStructure,
		Description:  `Short declarative clause, colon, then longer explanation — a mechanical LLM sentence pattern.`,
		Tip:          `Either merge into one flowing sentence, or make two separate sentences. The colon-elaboration structure becomes predictable when used repeatedly.`,
		CanRemove:    false,
		Color:        "#f472b6",
		BgColor:      "rgba(244,114,182,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Rewrite colon-elaboration sentences ("X: [long explanation]") by merging into one flowing sentence or splitting into two separate sentences.`,
		LLMDirective: `Do not use the '[short clause]: [long elaboration]' sentence structure — merge into one sentence or split into two.`,
	},
	{
		ID:           "question-then-answer",
		Name:         "Question-Then-Answer",
		Category:     types.CategorySentenceStructure,
		Description:  `Rhetorical question immediately followed by its own answer.`,
		Tip:          `Delete the question and just make the statement. "What does this mean? It means X." → "This means X."`,
		CanRemove:    false,
		Color:        "#34d399",
		BgColor:      "rgba(52,211,153,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Delete rhetorical questions and make the statement directly. "What does this mean? It means X." → "This means X."`,
		LLMDirective: `Do not write a rhetorical question immediately followed by its own answer — delete the question and make the statement directly.`,
	},
	{
		ID:           "staccato-burst",
		Name:         "Staccato Burst",
		Category:     types.CategorySentenceStructure,
		Description:  `Three or more consecutive very short sentences at matching cadence.`,
		Tip:          `Vary the rhythm. Combine some of these sentences, or expand one into a full thought. Uniform short sentences feel like a list of bullet points in disguise.`,
		CanRemove:    false,
		Color:        "#60a5fa",
		BgColor:      "rgba(96,165,250,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Break up staccato burst of short sentences by combining some or expanding one into a full thought with varied rhythm.`,
		LLMDirective: `Do not write three or more consecutive very short sentences at matching rhythm — vary sentence length and structure.`,
	},
	{
		ID:           "hedge-stack",
		Name:         "Hedge Stack",
		Category:     types.CategorySentenceStructure,
		Description:  `Multiple hedges in one sentence: "perhaps," "arguably," "might," "could," "seemingly," etc.`,
		Tip:          `Pick one hedge if you need it, remove the rest. Better: commit to the claim and let the reader evaluate it. Five hedges communicate nothing.`,
		CanRemove:    false,
		Color:        "#4ade80",
		BgColor:      "rgba(74,222,128,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Remove stacked hedges (perhaps, arguably, might, could, seemingly). Keep at most one if genuinely needed; otherwise commit to the claim.`,
		LLMDirective: `Do not stack multiple hedges in one sentence (perhaps, arguably, might, could, seemingly) — keep at most one.`,
	},
	{
		ID:           "parenthetical-qualifier",
		Name:         "Parenthetical Qualifier",
		Category:     types.CategorySentenceStructure,
		Description:  `Parenthetical asides that perform nuance without changing the argument.`,
		Tip:          `Either make the qualification part of the main sentence (it's important enough to say plainly) or delete it (it wasn't needed).`,
		CanRemove:    true,
		Color:        "#c084fc",
		BgColor:      "rgba(192,132,252,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Cut parenthetical qualifiers (of course, to be fair, admittedly, needless to say) — integrate if essential, delete otherwise.`,
		LLMDirective: `Remove the flagged parenthetical qualifiers (of course, to be fair, admittedly) — integrate the content or delete it.`,
	},
	{
		ID:           "unnecessary-contrast",
		Name:         "Unnecessary Contrast",
		Category:     types.CategorySentenceStructure,
		Description:  `"Whereas," "as opposed to," "unlike" used to restate what the first clause already implied.`,
		Tip:          `Delete the contrasting clause. If it adds information the reader didn't have, rewrite it as a direct statement rather than a contrast.`,
		CanRemove:    false,
		Color:        "#f87171",
		BgColor:      "rgba(248,113,113,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Remove unnecessary contrast markers (whereas, as opposed to, unlike, in contrast to) — restate as a direct claim.`,
		LLMDirective: `Do not use unnecessary contrast markers (whereas, as opposed to, unlike, in contrast to) — state the claim directly.`,
	},

	// ── Rhetorical ───────────────────────────────────────────────────────────
	{
		ID:           "important-to-note",
		Name:         `"It's Important to Note"`,
		Category:     types.CategoryRhetorical,
		Description:  `Verbal tic that precedes qualifications — tells the reader what to think before saying the thing.`,
		Tip:          `Delete the phrase and just say the thing. "It's important to note that X" → "X."`,
		CanRemove:    false,
		Color:        "#fbbf24",
		BgColor:      "rgba(251,191,36,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Delete "it is important to note", "it's worth noting", "it should be noted" — just say the thing.`,
		LLMDirective: `Do not use 'it is important to note', 'it\'s worth noting', or 'it should be noted' — just say the thing.`,
	},
	{
		ID:           "false-conclusion",
		Name:         "False Conclusion",
		Category:     types.CategoryRhetorical,
		Description:  `"At the end of the day," "in conclusion," "to summarize" — high-school essay signposting.`,
		Tip:          `Delete the phrase. The conclusion should land through its content, not be announced. If you need to say "in conclusion," the conclusion isn't clear enough.`,
		CanRemove:    false,
		Color:        "#e879f9",
		BgColor:      "rgba(232,121,249,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Delete conclusion signpost phrases (in conclusion, at the end of the day, to summarize, moving forward) — let the content land without announcement.`,
		LLMDirective: `Do not use conclusion signpost phrases (in conclusion, at the end of the day, to summarize, moving forward) — let the content land without announcement.`,
	},
	{
		ID:           "connector-addiction",
		Name:         "Connector Addiction",
		Category:     types.CategoryRhetorical,
		Description:  `Every paragraph opened with a transition word: "Furthermore," "Moreover," "Additionally," etc.`,
		Tip:          `Delete the transition and let the ideas connect through their content. If the connection isn't obvious without the word, restructure — don't signal.`,
		CanRemove:    false,
		Color:        "#2dd4bf",
		BgColor:      "rgba(45,212,191,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Delete paragraph-opening connectors (Furthermore, Moreover, Additionally, However, That said) — let the ideas connect through their content.`,
		LLMDirective: `Do not open paragraphs with transitional connectors (Furthermore, Moreover, Additionally, However, That said) — let ideas connect through their content.`,
	},

	// ── Structural ───────────────────────────────────────────────────────────
	{
		ID:           "listicle-instinct",
		Name:         "Listicle Instinct",
		Category:     types.CategoryStructural,
		Description:  `Lists with exactly 3, 5, 7, or 10 items — LLMs default to these magic numbers.`,
		Tip:          `Ask if this really needs a list. If the items have natural prose flow, write them as prose. If it is a list, let it have the number of items it actually has — 4, 6, 9.`,
		CanRemove:    false,
		Color:        "#fb923c",
		BgColor:      "rgba(251,146,60,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `If the list has natural prose flow, rewrite as prose. If keeping as a list, give it its natural number of items rather than a magic number.`,
		LLMDirective: `Do not use lists with exactly 3, 5, 7, or 10 items — write as prose or use the natural number of items.`,
	},

	// ── Sentence Structure (new) ─────────────────────────────────────────────
	{
		ID:           "serves-as",
		Name:         `"Serves As" Dodge`,
		Category:     types.CategorySentenceStructure,
		Description:  `Replacing "is/are" with pompous alternatives: "serves as," "stands as," "acts as," "functions as."`,
		Tip:          `Replace with "is" or "are." The pompous substitute performs sophistication without adding meaning.`,
		CanRemove:    false,
		Color:        "#818cf8",
		BgColor:      "rgba(129,140,248,0.18)",
		RequiresLLM:  false,
		RewriteHint:  `Replace "serves as", "stands as", "acts as", "functions as" with "is" or "are".`,
		LLMDirective: `Replace 'serves as', 'stands as', 'acts as', 'functions as' with 'is' or 'are'.`,
	},
	{
		ID:           "negation-countdown",
		Name:         `"Not X. Not Y. Just Z."`,
		Category:     types.CategorySentenceStructure,
		Description:  `2+ consecutive sentences starting with "Not " — building tension by negating before revealing.`,
		Tip:          `Cut the negations and state the positive claim directly.`,
		CanRemove:    false,
		Color:        "#fb7185",
		BgColor:      "rgba(251,113,133,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Replace the "Not X. Not Y. Just Z." pattern with a single direct positive statement.`,
		LLMDirective: `Do not use the "Not X. Not Y. Just Z." pattern — replace with a single direct positive statement.`,
	},
	{
		ID:           "anaphora-abuse",
		Name:         "Anaphora Abuse",
		Category:     types.CategorySentenceStructure,
		Description:  `3+ consecutive sentences starting with the same two-word opener.`,
		Tip:          `Vary the sentence openings. Anaphora becomes a tic when used more than twice.`,
		CanRemove:    false,
		Color:        "#22d3ee",
		BgColor:      "rgba(34,211,238,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Vary sentence openings — break the anaphoric repetition by restructuring some sentences.`,
		LLMDirective: `Do not repeat the same sentence opener three or more times consecutively — vary sentence openings.`,
	},
	{
		ID:           "gerund-litany",
		Name:         "Gerund Fragment Litany",
		Category:     types.CategorySentenceStructure,
		Description:  `2+ consecutive short sentences (≤8 words) starting with a capital -ing word.`,
		Tip:          `Expand these into full sentences or merge them. The gerund litany is a mechanical rhythm.`,
		CanRemove:    false,
		Color:        "#84cc16",
		BgColor:      "rgba(132,204,22,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Expand gerund sentence fragments into full sentences or merge them together.`,
		LLMDirective: `Do not write multiple consecutive short sentences starting with gerunds — expand or merge them.`,
	},
	{
		ID:           "superficial-analysis",
		Name:         "Superficial Analysis",
		Category:     types.CategorySentenceStructure,
		Description:  `Trailing participle phrase claiming false significance: ", highlighting its importance," ", underscoring its role," etc.`,
		Tip:          `Cut the trailing phrase entirely. If the significance is real, make it a separate sentence with a specific claim.`,
		CanRemove:    true,
		Color:        "#2dd4bf",
		BgColor:      "rgba(45,212,191,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Cut trailing significance phrases like ", highlighting its importance," ", underscoring its role," etc.`,
		LLMDirective: `Remove trailing significance phrases such as ', highlighting its importance,' or ', underscoring its role,' entirely.`,
	},

	// ── Rhetorical (new) ─────────────────────────────────────────────────────
	{
		ID:           "heres-the-kicker",
		Name:         `"Here's the Kicker"`,
		Category:     types.CategoryRhetorical,
		Description:  `False suspense transitions: "here's the kicker," "here's the thing," "here's where it gets interesting," etc.`,
		Tip:          `Delete the transition and state the point directly.`,
		CanRemove:    true,
		Color:        "#d946ef",
		BgColor:      "rgba(217,70,239,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Delete false suspense transitions ("Here's the thing", "Here's the kicker", "Here's where it gets interesting") and state the point directly.`,
		LLMDirective: `Do not use false suspense transitions ('Here\'s the thing', 'Here\'s the kicker', 'Here\'s where it gets interesting') — state the point directly.`,
	},
	{
		ID:           "pedagogical-aside",
		Name:         "Pedagogical Aside",
		Category:     types.CategoryRhetorical,
		Description:  `Teacher-mode phrases: "let's break this down," "let's unpack," "think of it as," etc.`,
		Tip:          `Skip the preamble and explain the thing directly. The reader doesn't need to be managed.`,
		CanRemove:    false,
		Color:        "#0ea5e9",
		BgColor:      "rgba(14,165,233,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Remove teacher-mode preambles ("let's break this down", "let's unpack", "think of it as") and explain directly.`,
		LLMDirective: `Do not use teacher-mode preambles ('Let\'s break this down', 'Let\'s unpack', 'Think of it as') — explain directly.`,
	},
	{
		ID:           "imagine-world",
		Name:         `"Imagine a World Where"`,
		Category:     types.CategoryRhetorical,
		Description:  `Opens with a futurist invitation: "Imagine a world," "Imagine if you," "Imagine what would," "Imagine a future."`,
		Tip:          `Start with the actual argument instead of inviting the reader to imagine it.`,
		CanRemove:    false,
		Color:        "#7c3aed",
		BgColor:      "rgba(124,58,237,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Delete "Imagine a world where..." opener and start with the actual argument.`,
		LLMDirective: `Do not open with hypothetical world-building ('Imagine a world where...') — start with the actual argument.`,
	},
	{
		ID:           "vague-attribution",
		Name:         "Vague Attribution",
		Category:     types.CategoryRhetorical,
		Description:  `Unnamed authority invocations: "experts argue," "studies show," "observers have noted," "research suggests," etc.`,
		Tip:          `Name the experts, cite the studies, or drop the claim. Vague attribution is worse than no citation.`,
		CanRemove:    false,
		Color:        "#64748b",
		BgColor:      "rgba(100,116,139,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Replace vague attribution (experts argue, studies show, research suggests) with a named source, or drop the claim entirely.`,
		LLMDirective: `Do not use vague attribution ('experts argue', 'studies show', 'research suggests') — name the source or drop the claim.`,
	},
	{
		ID:           "despite-challenges",
		Name:         `"Despite Its Challenges"`,
		Category:     types.CategoryRhetorical,
		Description:  `Formula: "Despite [these/its/the] [challenges/obstacles/limitations]..." — conceding without substance.`,
		Tip:          `Name the specific challenge. "Despite its challenges" is a throat-clear disguised as an acknowledgment.`,
		CanRemove:    false,
		Color:        "#10b981",
		BgColor:      "rgba(16,185,129,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Replace "despite its/these challenges" with the specific named challenge, or cut the concession.`,
		LLMDirective: `Do not use 'despite its challenges', 'despite these limitations', or similar empty concessions — name the specific challenge or cut it.`,
	},

	// ── Structural (new) ─────────────────────────────────────────────────────
	{
		ID:           "listicle-trench-coat",
		Name:         "Listicle in a Trench Coat",
		Category:     types.CategoryStructural,
		Description:  `"The first... The second... The third..." — prose disguising a list.`,
		Tip:          `Either use an actual list or rewrite as genuine prose. Don't pretend a list is an argument.`,
		CanRemove:    false,
		Color:        "#f97316",
		BgColor:      "rgba(249,115,22,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Rewrite "The first... The second... The third..." as either a real bullet list or genuine prose where ideas connect through logic rather than ordinal markers.`,
		LLMDirective: `Do not use ordinal prose disguising a list ("The first... The second... The third...") — write as real prose or use an actual list.`,
	},
	{
		ID:           "bold-first-bullets",
		Name:         "Bold-First Bullets",
		Category:     types.CategoryStructural,
		Description:  `Markdown list items starting with a bolded phrase: "- **Term**: explanation."`,
		Tip:          `Either use a definition list format or integrate the bold label into prose. This is pure LLM document structure.`,
		CanRemove:    false,
		Color:        "#ca8a04",
		BgColor:      "rgba(202,138,4,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Rewrite bold-first bullet points as prose sentences that integrate the label naturally.`,
		LLMDirective: `Do not use bold-first bullet formatting (**Term**: explanation) — integrate into prose.`,
	},
	{
		ID:           "unicode-arrows",
		Name:         "Unicode Decoration",
		Category:     types.CategoryStructural,
		Description:  `The → arrow character used in prose as a decoration or shorthand.`,
		Tip:          `Write out the relationship. "Input → Output" → "Input produces Output."`,
		CanRemove:    false,
		Color:        "#475569",
		BgColor:      "rgba(71,85,105,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Replace → arrows with the written-out relationship (produces, leads to, becomes, results in).`,
		LLMDirective: `Do not use → arrows in prose — write out the relationship (produces, leads to, becomes).`,
	},
	{
		ID:           "dramatic-fragment",
		Name:         "Dramatic Fragment",
		Category:     types.CategoryStructural,
		Description:  `A standalone paragraph with ≤4 words — used for false dramatic emphasis.`,
		Tip:          `Either expand it into a real sentence or absorb it into the surrounding paragraph.`,
		CanRemove:    false,
		Color:        "#f43f5e",
		BgColor:      "rgba(244,63,94,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Absorb this short dramatic fragment into the surrounding paragraph or expand it into a complete thought.`,
		LLMDirective: `Do not use a one-to-four-word standalone paragraph for dramatic emphasis — absorb it into the surrounding text.`,
	},

	// ── Framing (new) ────────────────────────────────────────────────────────
	{
		ID:           "concept-label",
		Name:         "Invented Concept Label",
		Category:     types.CategoryFraming,
		Description:  `Compound noun + abstract suffix used as an invented analytical term: "the attention paradox," "the trust vacuum," "the context creep."`,
		Tip:          `Either explain the phenomenon in plain terms or use an established name for it.`,
		CanRemove:    false,
		Color:        "#c084fc",
		BgColor:      "rgba(192,132,252,0.15)",
		RequiresLLM:  false,
		RewriteHint:  `Replace invented concept labels ("the X paradox", "the Y vacuum") with plain description of the actual phenomenon.`,
		LLMDirective: `Do not use invented concept labels ('the X paradox', 'the Y vacuum', 'the Z creep') — describe the phenomenon in plain terms.`,
	},

	// ── LLM-required semantic detections ─────────────────────────────────────
	{
		ID:               "triple-construction",
		Name:             "Triple Construction",
		Category:         types.CategorySentenceStructure,
		Description:      `Exactly three parallel items: "X, Y, and Z" — LLMs default to threes compulsively.`,
		Tip:              `Break the pattern. Use two items or four. Or convert one item into its own sentence to give it more weight.`,
		CanRemove:        false,
		Color:            "#a3e635",
		BgColor:          "rgba(163,230,53,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `Exactly 3 parallel grammatical items where the items are structurally parallel phrases. This includes the classic "X, Y, and Z" comma-list form, and also "from X to Y to Z" / "from X to Y and Z" constructions where three parallel noun phrases or clauses are stacked. Do not flag 2-item or 4+ item lists.`,
		RewriteHint:      `Break the rule-of-three pattern (X, Y, and Z) — use two items, four items, or give one item its own sentence.`,
		LLMDirective:     `Do not use the rule of three (X, Y, and Z) — use two items, four items, or give one item its own sentence.`,
	},
	{
		ID:               "throat-clearing",
		Name:             "Throat-Clearing Opener",
		Category:         types.CategoryRhetorical,
		Description:      `First paragraph that adds no information and could be deleted without any loss.`,
		Tip:              `Delete the whole paragraph and start at the second one. The real piece almost always begins at the second paragraph.`,
		CanRemove:        true,
		Color:            "#f472b6",
		BgColor:          "rgba(244,114,182,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `An opening paragraph that adds zero information and could be deleted without any loss of meaning. Flag only if it's the very first paragraph.`,
		RewriteHint:      `Delete this opening paragraph entirely — it adds no information and the piece starts properly at the next paragraph.`,
		LLMDirective:     `Delete this paragraph entirely — it adds no information; the piece starts properly at the next paragraph.`,
	},
	{
		ID:               "sycophantic-frame",
		Name:             "Sycophantic Frame",
		Category:         types.CategoryRhetorical,
		Description:      `Opening that compliments the question or topic before addressing it.`,
		Tip:              `Delete the compliment entirely. "Great question! X is important because…" → "X is important because…"`,
		CanRemove:        true,
		Color:            "#fdba74",
		BgColor:          "rgba(253,186,116,0.18)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `Text that opens by complimenting the question, assignment, or topic ("Great question," "This is a fascinating topic," etc.).`,
		RewriteHint:      `Delete the complimentary opener ("Great question!", "This is a fascinating topic") and start with the actual content.`,
		LLMDirective:     `Delete the complimentary opener ('Great question!', 'This is fascinating') — start with the actual content.`,
	},
	{
		ID:               "balanced-take",
		Name:             "Balanced Take",
		Category:         types.CategoryRhetorical,
		Description:      `Every argument immediately followed by a concession that softens it to nothing.`,
		Tip:              `Make the argument. Acknowledge genuine counterarguments separately and specifically. Don't reflexively soften every claim — it reads as epistemic cowardice.`,
		CanRemove:        false,
		Color:            "#86efac",
		BgColor:          "rgba(134,239,172,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `A sentence that makes a point then immediately softens it into nothing — reflexive RLHF-style hedging that negates the original claim.`,
		RewriteHint:      `Remove reflexive hedging that immediately softens every claim. State the argument, then deal with genuine counterarguments separately.`,
		LLMDirective:     `Do not reflexively soften every claim with an immediate concession — state the argument, then address genuine counterarguments separately.`,
	},
	{
		ID:               "unnecessary-elaboration",
		Name:             "Unnecessary Elaboration",
		Category:         types.CategorySentenceStructure,
		Description:      `The sentence makes its point, then keeps going to restate it.`,
		Tip:              `Cut at the point where the sentence was done. The restatement dilutes the original impact.`,
		CanRemove:        false,
		Color:            "#fca5a5",
		BgColor:          "rgba(252,165,165,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `A sentence that continues past the point where it was already finished, restating its own point in slightly different words within the same sentence or immediately adjacent clause. Example: "The reform failed. It did not succeed, and the attempt to change things did not work out as intended." — the second sentence adds nothing the first didn't already say. This is strictly a within-sentence or single-sentence pattern. Do NOT flag cross-paragraph patterns (that is one-point-dilution, a separate rule). Do NOT flag an analogy or concept introduced in one paragraph being purposefully extended or applied to a new domain in a subsequent paragraph — that is development, not elaboration.`,
		RewriteHint:      `Cut sentences at the point where they were already done — remove restatements that add no new information.`,
		LLMDirective:     `Do not restate a point in the same sentence or adjacent clause after already making it — stop when the sentence is done.`,
	},
	{
		ID:               "empathy-performance",
		Name:             "Empathy Performance",
		Category:         types.CategoryRhetorical,
		Description:      `Generic emotional language ("I understand this can be difficult") applicable to any topic.`,
		Tip:              `Delete it, or replace with something specific to this exact situation. Generic empathy is indistinguishable from no empathy.`,
		CanRemove:        true,
		Color:            "#93c5fd",
		BgColor:          "rgba(147,197,253,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `Generic emotional language applicable to any situation ("I understand this can be difficult," "Your feelings are valid," etc.).`,
		RewriteHint:      `Delete generic empathy phrases or replace with something specific to this exact situation.`,
		LLMDirective:     `Do not use generic empathy language ('I understand this can be difficult') — delete it or replace with something specific.`,
	},
	{
		ID:               "pivot-paragraph",
		Name:             "Pivot Paragraph",
		Category:         types.CategoryStructural,
		Description:      `A one-sentence paragraph containing no new information, only transition.`,
		Tip:              `Delete it. Attach the transition thought to either the paragraph before or after, or cut it entirely — the surrounding content should do this work.`,
		CanRemove:        true,
		Color:            "#c4b5fd",
		BgColor:          "rgba(196,181,253,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `A one-sentence paragraph containing zero new information — only transitions between surrounding paragraphs.`,
		RewriteHint:      `Delete this transition-only paragraph — the surrounding content should do this work.`,
		LLMDirective:     `Delete this transition-only paragraph — it contains no new information.`,
	},
	{
		ID:               "false-range",
		Name:             "False Range",
		Category:         types.CategorySentenceStructure,
		Description:      `"From X to Y" constructions where X and Y aren't on a meaningful spectrum, or hollow idioms like "doesn't emerge from nowhere".`,
		Tip:              `Either show a real spectrum or cut the framing entirely.`,
		CanRemove:        false,
		Color:            "#fbbf24",
		BgColor:          "rgba(251,191,36,0.15)",
		RequiresLLM:      false,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `A "from X to Y" construction where X and Y are not on any meaningful spectrum or scale — used as a fancy way to list two loosely related things rather than express a genuine range. Also flag hollow idioms like "doesn't come from nowhere" / "doesn't emerge from nowhere" that use "from" as clichéd filler. Flag only clear cases. For matchedText, capture the full verb phrase containing the hollow construction (e.g. "doesn't emerge from nowhere"), not just the prepositional fragment.`,
		RewriteHint:      `Replace hollow "from X to Y" constructions with direct language. Cut "doesn't come from nowhere" and similar clichés.`,
		LLMDirective:     `Do not use hollow 'from X to Y' constructions or clichéd idioms like 'doesn't come from nowhere' — use direct language.`,
	},
	{
		ID:               "grandiose-stakes",
		Name:             "Grandiose Stakes",
		Category:         types.CategoryFraming,
		Description:      `Inflating the stakes of an ordinary argument to world-historical significance without substantiation.`,
		Tip:              `Scale the claim to match the evidence. If it's not world-historical, don't say so.`,
		CanRemove:        false,
		Color:            "#ef4444",
		BgColor:          "rgba(239,68,68,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `Inflating the significance of an ordinary point to world-historical importance ("will fundamentally reshape how we think about everything", "will define the next era of computing", "has implications for the future of humanity") without substantiation.`,
		RewriteHint:      `Scale the claim to match the actual evidence — remove world-historical inflation and state what it actually means.`,
		LLMDirective:     `Do not inflate ordinary points to world-historical significance — scale the claim to match the actual evidence.`,
	},
	{
		ID:               "historical-analogy",
		Name:             "Historical Analogy Stack",
		Category:         types.CategoryRhetorical,
		Description:      `Rapid-fire listing of famous companies or tech revolutions to build false authority by association.`,
		Tip:              `Pick one analogy and develop it. A list of analogies proves nothing — it just borrows the aura of many things.`,
		CanRemove:        false,
		Color:            "#3b82f6",
		BgColor:          "rgba(59,130,246,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `Rapid-fire listing of famous companies or tech revolutions stacked together to build false authority by association ("Apple didn't build Uber. Facebook didn't build Spotify..."; "the web, mobile, social, cloud, AI"). Flag when the historical references are decorative rather than analytically necessary.`,
		RewriteHint:      `Replace rapid-fire historical name-dropping with one specific analogy developed in detail, or drop the analogy and make the point directly.`,
		LLMDirective:     `Do not stack rapid-fire historical or company analogies — develop one analogy or drop them entirely.`,
	},
	{
		ID:               "false-vulnerability",
		Name:             "False Vulnerability",
		Category:         types.CategoryRhetorical,
		Description:      `Performative self-awareness or simulated honesty ("I'll be honest," "Let's be real") that reads as staged rather than genuine.`,
		Tip:              `Real vulnerability is specific and uncomfortable. If it sounds polished, cut it.`,
		CanRemove:        false,
		Color:            "#a855f7",
		BgColor:          "rgba(168,85,247,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierSentence,
		LLMDetectionHint: `Performative self-awareness or simulated honesty that reads as staged rather than genuine ("And yes, I'll admit...", "I'll be honest with you", "Let's be real:", "And yes, since we're being honest"). Real vulnerability is specific and uncomfortable; flag when it sounds polished and risk-free.`,
		RewriteHint:      `Remove performative honesty phrases ("I'll be honest", "Let's be real") — they signal inauthenticity. If vulnerable, be specific.`,
		LLMDirective:     `Do not use performative honesty phrases ('I\'ll be honest', 'Let\'s be real', 'And yes, since we\'re being honest') — real vulnerability is specific.`,
	},

	// ── Document-level (Sonnet) ───────────────────────────────────────────────
	{
		ID:               "dead-metaphor",
		Name:             "Dead Metaphor",
		Category:         types.CategoryFraming,
		Description:      `The same metaphor or image recurs throughout the piece, becoming mechanical rather than intentional.`,
		Tip:              `Keep the instance that earns its place most and cut the rest. The same image used five times is no longer a choice.`,
		CanRemove:        false,
		Color:            "#fb923c",
		BgColor:          "rgba(251,146,60,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierDocument,
		LLMDetectionHint: `The same metaphor, image, or conceptual frame recurs 3 or more times across the piece mechanically rather than intentionally. A single metaphor is a choice; the same one appearing every few paragraphs is a crutch. Flag a later instance (not the first), since repetition is the problem.`,
		RewriteHint:      `Remove this repeated metaphor — use it once where it earns its place, or replace with a fresh image or plain language.`,
		LLMDirective:     `Do not repeat the flagged metaphor — use it once where it earns its place or replace with plain language.`,
	},
	{
		ID:               "one-point-dilution",
		Name:             "One-Point Dilution",
		Category:         types.CategoryStructural,
		Description:      `The same core argument restated across multiple paragraphs with different words but no new information.`,
		Tip:              `Find where the point was made best and cut every restatement. A strong claim once beats the same claim eight times.`,
		CanRemove:        false,
		Color:            "#94a3b8",
		BgColor:          "rgba(148,163,184,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierDocument,
		LLMDetectionHint: `The same core claim or argument appears across multiple paragraphs restated with different words, examples, or metaphors, but adding no new information. The piece pads a simple thesis. Flag the most redundant restatement — a sentence or clause that says something already said.`,
		RewriteHint:      `Cut this restatement — the point was already made. If adding it, it must introduce genuinely new information.`,
		LLMDirective:     `Do not restate the same core argument in different words — add new information or cut the restatement.`,
	},
	{
		ID:               "fractal-summaries",
		Name:             "Fractal Summaries",
		Category:         types.CategoryStructural,
		Description:      `Meta-commentary that previews or recaps content rather than delivering it: "In this section we'll explore...", "As we've seen..."`,
		Tip:              `Delete the signpost and say the thing. The content should do this work.`,
		CanRemove:        true,
		Color:            "#6366f1",
		BgColor:          "rgba(99,102,241,0.15)",
		RequiresLLM:      true,
		LLMTier:          types.LLMTierDocument,
		LLMDetectionHint: `Meta-commentary that previews or recaps content rather than delivering it: "In this section, we will explore...", "As we have seen...", "To summarize what we have covered...", "What follows is an examination of...". Flag only genuine content-free structural signposting, not substantive transitions.`,
		RewriteHint:      `Delete structural signposting ("In this section we will...", "As we've seen...") and say the thing directly.`,
		LLMDirective:     `Do not use structural signposting that previews or recaps content ('In this section we will...', 'As we\'ve seen...') — say the thing directly.`,
	},
}

// ByID maps each rule's identifier to its definition.
var ByID = func() map[string]types.ViolationRule {
	m := make(map[string]types.ViolationRule, len(All))
	for _, r := range All {
		m[r.ID] = r
	}
	return m
}()
