#!/bin/bash
# GENERATED by cc-guides from .claude/fragments/scripts/install-binary.sh/ — do not edit; edit the fragments and push — CI renders.
# Locate the binrun runner and exec the slop-cop descriptor.
#
# This renders to plugin scripts/install-binary.sh — the successor to the
# provision-a-symlink installer. bin/slop-cop is a committed symlink to it, so
# hooks, MCP servers, and the CLI reach this script with the tool's own
# arguments. Its whole job is to find binrun — on PATH, at the shared
# ~/.daemonkit/bin/binrun, or by a one-time virgin-machine bootstrap of the
# pinned runner release — and hand off to "binrun <descriptor> $@", which
# resolves and execs the version-exact artifact the sidecar bin/slop-cop.binrun
# descriptor pins. Every failure here exits 1: exit 2 is reserved for a real
# hook verdict, and the only other codes come from the exec'd artifact itself.
#
# bash, not sh: this runs once per hook invocation, and an endpoint-security agent
# that deep-inspects /bin/sh as a living-off-the-land interpreter can put seconds on
# every exec of it. The body is POSIX either way.
set -eu

# --- Central runner pin: edited here, in cc-skills, for the whole fleet --------
# Pinned to a binrun release: RUNNER_TAG and the four digests are the release tag
# and its checksums.txt sha256 values for binrun_<version>_<os>_<arch>.tar.gz.
# Bump all five together when adopting a newer binrun.
RUNNER_REPO="yasyf/binrun"
RUNNER_TAG="v0.1.1"
RUNNER_SHA_darwin_arm64="11a6ed5837171e8ae1b005f14be0fdd79286ef6bce039362bcfad7c944b9abdf"
RUNNER_SHA_darwin_amd64="b168fd14d1c87d6457aaa064243fba53ac9fc83a1a084df615e6e426a7f8e157"
RUNNER_SHA_linux_amd64="e33d95055002e1ebff80db5bb175e60ee0be83f031778a659e29ab3f8bffb7ec"
RUNNER_SHA_linux_arm64="7a1fff9270843f66df1a41edccb5d7f1c61e94da024d501634c2f888fa7d2929"
# ------------------------------------------------------------------------------

# ${0%/*}, not dirname: skips an exec an endpoint-security agent can serialize fleet-wide.
case "$0" in */*) d=${0%/*} ;; *) d=. ;; esac
ROOT="$(cd "$d/.." && pwd)"
DESCRIPTOR="$ROOT/bin/slop-cop.binrun"
# binrun execs the cached artifact out of ~/.daemonkit/cache/<xx>/<digest>/, so the
# exec'd binary cannot derive the plugin root from its own path. Export it: a tool
# that overrides its embedded copies with plugin-root files reads this first.
export BINRUN_PLUGIN_ROOT="$ROOT"
RUNNER_HOME="${DAEMONKIT_HOME:-$HOME/.daemonkit}"
RUNNER_BIN="$RUNNER_HOME/bin/binrun"

fail() {
  echo "slop-cop: $1" >&2
  exit 1
}

# Arm 1: binrun already on PATH (brew-installed for humans, or a dev build).
if binrun="$(command -v binrun 2>/dev/null)"; then
  exec "$binrun" "$DESCRIPTOR" "$@"
fi

# Arm 2: the shared daemonkit-managed runner a previous bootstrap installed.
if [ -x "$RUNNER_BIN" ]; then
  exec "$RUNNER_BIN" "$DESCRIPTOR" "$@"
fi

# Arm 3: virgin machine — download the pinned runner release, sha256-verify it,
# install it atomically to the shared bin, and exec. Mirrors the exact-release
# curl+verify semantics of install-binary-pinned's final arm.
case "$RUNNER_TAG" in
  v0.0.0-unreleased) fail "binrun is not released yet (RUNNER_TAG is unpinned) and no runner is installed" ;;
esac

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$os" in
  darwin | linux) ;;
  *) fail "unsupported OS '$os'" ;;
esac
arch="$(uname -m)"
case "$arch" in
  x86_64 | amd64) arch=amd64 ;;
  arm64 | aarch64) arch=arm64 ;;
  *) fail "unsupported architecture '$arch'" ;;
esac
case "${os}_${arch}" in
  darwin_arm64) expected="$RUNNER_SHA_darwin_arm64" ;;
  darwin_amd64) expected="$RUNNER_SHA_darwin_amd64" ;;
  linux_amd64) expected="$RUNNER_SHA_linux_amd64" ;;
  linux_arm64) expected="$RUNNER_SHA_linux_arm64" ;;
esac

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

asset="binrun_${RUNNER_TAG#v}_${os}_${arch}.tar.gz"
url="https://github.com/$RUNNER_REPO/releases/download/$RUNNER_TAG/$asset"

mkdir -p "$RUNNER_HOME/bin"
# Stage on the destination filesystem and rename into place: an interrupted
# bootstrap never leaves a half-written runner, the rename is atomic, and
# concurrent bootstraps converge on a single copy without a lock. Renaming over
# a running binrun keeps its inode alive (unlike an in-place write, which fails
# ETXTBSY on Linux).
tmpd="$(mktemp -d "$RUNNER_HOME/bin/.binrun.XXXXXX")"
trap 'rm -rf "$tmpd"' EXIT
curl -fsSL --retry 2 --connect-timeout 10 --max-time 300 -o "$tmpd/$asset" "$url" \
  || fail "could not download the pinned binrun runner ($url)"
actual="$(sha256_of "$tmpd/$asset")"
[ "$actual" = "$expected" ] \
  || fail "binrun runner checksum mismatch for $asset (expected $expected, got $actual)"
tar -xzf "$tmpd/$asset" -C "$tmpd" \
  || fail "could not extract $asset"
[ -x "$tmpd/binrun" ] \
  || fail "$asset did not contain a binrun executable"
mv -f "$tmpd/binrun" "$RUNNER_BIN"
rm -rf "$tmpd"
trap - EXIT
exec "$RUNNER_BIN" "$DESCRIPTOR" "$@"
