#!/bin/bash
# GENERATED by cc-guides from .claude/fragments/scripts/install-binary.sh/ — do not edit; edit the fragments and push — CI renders.
# Locate the binrun runner and exec the slop-cop descriptor.
#
# This renders to plugin scripts/install-binary.sh — the successor to the
# provision-a-symlink installer. bin/slop-cop is a committed symlink to it, so
# hooks, MCP servers, and the CLI reach this script with the tool's own
# arguments. Its whole job is to find binrun — named in BINRUN_BIN, installed at
# the pinned tag under ~/.daemonkit/binrun/<tag>, on PATH, or bootstrapped once
# from the pinned release — and hand off to "binrun <descriptor> $@", which
# resolves and execs the version-exact artifact the sidecar bin/slop-cop.binrun
# descriptor pins. Every failure here exits 1: exit 2 is reserved for a real
# hook verdict, and the only other codes come from the exec'd artifact itself.
#
# bash, not sh: this runs once per hook invocation, and an endpoint-security agent
# that deep-inspects /bin/sh as a living-off-the-land interpreter can put seconds on
# every exec of it. The body is POSIX either way.
set -eu

# --- Central runner pin: edited here, in cc-skills, for the whole fleet --------
# Pinned to a binrun release: RUNNER_TAG and the four digests are the release tag
# and its checksums.txt sha256 values for binrun_<version>_<os>_<arch>.tar.gz.
# Bump all five together when adopting a newer binrun.
RUNNER_REPO="yasyf/binrun"
RUNNER_TAG="v0.8.0"
RUNNER_SHA_darwin_arm64="be67dab089951cae4d1abfdbcadebf79ef2c706d83235302de0962c3b5d23fbd"
RUNNER_SHA_darwin_amd64="7ee512c05d587dc56bcd363cb3b3c3e5495a525879314bc5b6dd6ecf08c23319"
RUNNER_SHA_linux_amd64="45084812f87f3451b0ad30985d5ce766738f41ff2c3e8464739117c251e86256"
RUNNER_SHA_linux_arm64="bb622f2c119ca9bd6f3c3f94e2658116c27b4e703c30005ea17da521f820f899"
# ------------------------------------------------------------------------------

# ${0%/*}, not dirname: skips an exec an endpoint-security agent can serialize fleet-wide.
case "$0" in */*) d=${0%/*} ;; *) d=. ;; esac
ROOT="$(cd "$d/.." && pwd)"

is_version() {
  case "$1" in "" | *[!0-9.]* | .* | *. | *..*) return 1 ;; esac
}

version_gt() {
  va=$1 vb=$2
  while [ -n "$va$vb" ]; do
    ca=${va%%.*} cb=${vb%%.*}
    [ "${ca:-0}" -eq "${cb:-0}" ] || { [ "${ca:-0}" -gt "${cb:-0}" ]; return; }
    case "$va" in *.*) va=${va#*.} ;; *) va= ;; esac
    case "$vb" in *.*) vb=${vb#*.} ;; *) vb= ;; esac
  done
  return 1
}

# Sessions keep a replaced plugin's bin/ on PATH; hand off to the newest version
# dir Claude Code has not marked .orphaned_at. Hops only go up, so they terminate.
if [ -e "$ROOT/.orphaned_at" ] && is_version "${ROOT##*/}"; then
  newest=$ROOT
  for sibling in "${ROOT%/*}"/*/; do
    sibling=${sibling%/}
    is_version "${sibling##*/}" || continue
    [ ! -e "$sibling/.orphaned_at" ] && [ -x "$sibling/bin/slop-cop" ] || continue
    if version_gt "${sibling##*/}" "${newest##*/}"; then
      newest=$sibling
    fi
  done
  [ "$newest" = "$ROOT" ] || exec "$newest/bin/slop-cop" "$@"
fi

DESCRIPTOR="$ROOT/bin/slop-cop.binrun"
# binrun execs the cached artifact out of ~/.daemonkit/cache/<xx>/<digest>/, so the
# exec'd binary cannot derive the plugin root from its own path. Export it: a tool
# that overrides its embedded copies with plugin-root files reads this first.
export BINRUN_PLUGIN_ROOT="$ROOT"

fail() {
  echo "slop-cop: $1" >&2
  exit 1
}

# daemonkit's realhome: DAEMONKIT_HOME names a home directory, and its fallback is
# the passwd home, not $HOME. binrun resolves its cache the same way.
passwd_user="$(id -un)"
eval "passwd_home=~$passwd_user"
# An unexpanded tilde means the name has no passwd entry to take a home from.
case "$passwd_home" in \~*) fail "no passwd home for '$passwd_user'" ;; esac
RUNNER_HOME="${DAEMONKIT_HOME:-$passwd_home}/.daemonkit"
RUNNER_DIR="$RUNNER_HOME/binrun/$RUNNER_TAG"
RUNNER_BIN="$RUNNER_DIR/binrun"

# Arm 1: an explicitly chosen runner — a dev build, named on purpose.
if [ -n "${BINRUN_BIN:-}" ]; then
  exec "$BINRUN_BIN" "$DESCRIPTOR" "$@"
fi

# Arm 2: the runner a previous bootstrap installed at the pinned tag, in a
# directory of its own so plugins pinning different tags never replace it.
if [ -x "$RUNNER_BIN" ]; then
  exec "$RUNNER_BIN" "$DESCRIPTOR" "$@"
fi

# Arm 3: a binrun on PATH. It carries no stamp, so it ranks below the pinned
# runner: an older one rejects a descriptor whose source the pin was raised for.
if binrun="$(command -v binrun 2>/dev/null)"; then
  exec "$binrun" "$DESCRIPTOR" "$@"
fi

# Arm 4: virgin machine — download the pinned runner release, sha256-verify it,
# install it atomically to the shared bin, and exec. Mirrors the exact-release
# curl+verify semantics of install-binary-pinned's final arm.
case "$RUNNER_TAG" in
  v0.0.0-unreleased) fail "binrun is not released yet (RUNNER_TAG is unpinned) and no runner is installed" ;;
esac

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$os" in
  darwin | linux) ;;
  *) fail "unsupported OS '$os'" ;;
esac
arch="$(uname -m)"
case "$arch" in
  x86_64 | amd64) arch=amd64 ;;
  arm64 | aarch64) arch=arm64 ;;
  *) fail "unsupported architecture '$arch'" ;;
esac
case "${os}_${arch}" in
  darwin_arm64) expected="$RUNNER_SHA_darwin_arm64" ;;
  darwin_amd64) expected="$RUNNER_SHA_darwin_amd64" ;;
  linux_amd64) expected="$RUNNER_SHA_linux_amd64" ;;
  linux_arm64) expected="$RUNNER_SHA_linux_arm64" ;;
esac

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

asset="binrun_${RUNNER_TAG#v}_${os}_${arch}.tar.gz"
url="https://github.com/$RUNNER_REPO/releases/download/$RUNNER_TAG/$asset"

mkdir -p "$RUNNER_DIR"
# Stage on the destination filesystem and rename into place: an interrupted
# bootstrap never leaves a half-written runner, the rename is atomic, and
# concurrent bootstraps of one tag converge on identical bytes without a lock.
# Renaming over a running binrun keeps its inode alive (unlike an in-place
# write, which fails ETXTBSY on Linux).
tmpd="$(mktemp -d "$RUNNER_DIR/.binrun.XXXXXX")"
trap 'rm -rf "$tmpd"' EXIT
curl -fsSL --retry 2 --connect-timeout 10 --max-time 300 -o "$tmpd/$asset" "$url" \
  || fail "could not download the pinned binrun runner ($url)"
actual="$(sha256_of "$tmpd/$asset")"
[ "$actual" = "$expected" ] \
  || fail "binrun runner checksum mismatch for $asset (expected $expected, got $actual)"
tar -xzf "$tmpd/$asset" -C "$tmpd" \
  || fail "could not extract $asset"
[ -x "$tmpd/binrun" ] \
  || fail "$asset did not contain a binrun executable"
mv -f "$tmpd/binrun" "$RUNNER_BIN"
rm -rf "$tmpd"
trap - EXIT
exec "$RUNNER_BIN" "$DESCRIPTOR" "$@"
