package detectors

import (
	"strings"
	"testing"

	"github.com/yasyf/slop-cop/internal/types"
)

// A 46-word sentence: the long-sentence fixture every length case derives from.
const longSentence = "The pipeline reads the source file from disk and then hands the bytes " +
	"to the analyzer, which masks every span that is not prose, and after that the detectors " +
	"run in order over the masked copy and each one emits its own violations for the report."

func TestDetectLongSentence(t *testing.T) {
	runHits(t, "long-sentence", DetectLongSentence, []hitCase{
		{"over budget", longSentence, true},
		{"under budget", "The pipeline reads the source file from disk and hands the bytes to the analyzer.", false},
		{
			"parenthetical collapses under budget",
			"The pipeline reads the source file from disk and then hands the bytes " +
				"to the analyzer (which masks every span that is not prose before anything else runs), " +
				"and then each detector emits its own violations for the report.", false,
		},
		{
			"quoted span collapses under budget",
			"The parser rejects the header when the value reads \"one two three four five six seven " +
				"eight nine ten eleven twelve thirteen fourteen fifteen sixteen\" and it stops there " +
				"before the body is read at all by anyone.", false,
		},
		{
			"pipe table row skipped",
			"| " + strings.ReplaceAll(longSentence, " ", " | ") + " |", false,
		},
		{"ATX heading line skipped", "# " + longSentence, false},
		{
			"list shape skipped",
			"- The pipeline reads the source file from disk and then hands the bytes to the analyzer\n" +
				"- which masks every span that is not prose, and after that the detectors run in order\n" +
				"- over the masked copy and each one emits its own violations for the report", false,
		},
	})
}

func TestDetectLongSentenceSpanExcludesTrailingSpace(t *testing.T) {
	v := DetectLongSentence(longSentence + "\n\nShort tail.\n")
	if len(v) != 1 {
		t.Fatalf("got %d violations, want 1", len(v))
	}
	if got := v[0].MatchedText; got != longSentence {
		t.Fatalf("span = %q, want the sentence with no trailing whitespace", got)
	}
	if v[0].Explanation != "46 words" {
		t.Fatalf("explanation = %q, want %q", v[0].Explanation, "46 words")
	}
}

func TestDetectLongParagraph(t *testing.T) {
	seven := "One runs. Two runs. Three runs. Four runs. Five runs. Six runs. Seven runs."
	six := "One runs. Two runs. Three runs. Four runs. Five runs. Six runs."
	runHits(t, "long-paragraph", DetectLongParagraph, []hitCase{
		{"seven sentences", seven, true},
		{"six sentences", six, false},
		{
			"abbreviation re-merged under budget",
			"One runs on a file, e.g. README.md, and stops. Two runs. Three runs. " +
				"Four runs. Five runs. Six runs.", false,
		},
		{
			"initial re-merged under budget",
			"The author is J. R. R. Tolkien. Two runs. Three runs. Four runs. Five runs. Six runs.", false,
		},
		{
			"list shape skipped",
			"- One runs.\n- Two runs.\n- Three runs.\n- Four runs.\n- Five runs.\n- Six runs.\n- Seven runs.", false,
		},
		{
			"pipe table skipped",
			"| a | b |\n| --- | --- |\n| One runs. | Two runs. |\n| Three runs. | Four runs. |\n" +
				"| Five runs. | Six runs. |\n| Seven runs. | Eight runs. |", false,
		},
		{"heading-led paragraph skipped", "# " + seven, false},
	})
}

func TestDetectPassiveVoice(t *testing.T) {
	runHits(t, "passive-voice", DetectPassiveVoice, []hitCase{
		{"regular participle", "The report is generated by the analyzer.", true},
		{"past tense", "The file was written by a script.", true},
		{"irregular participle", "The value is given by the caller.", true},
		{"one adverb", "The setting is quietly overridden by the plugin.", true},
		{"two adverbs", "The cache is very rarely cleared by the daemon.", true},
		{"negated", "The flag is not honoured by the runner.", true},
		{"plural agent", "Every rule is reviewed by two maintainers.", true},
		{"predicate adjective", "The runner is tired.", false},
		{"interested in", "She is interested in the result.", false},
		{"complicated by the fact", "The setup is complicated by the fact that two tools disagree.", false},
		{"by default", "Colour is disabled by default.", false},
		{"by design", "The retry is skipped by design.", false},
		{"instrumental gerund", "The threshold is adjusted by setting the flag.", false},
		{"passed by reference", "The struct is passed by reference.", false},
		{"no agent", "The report is generated nightly.", false},
		{"active voice", "The analyzer generates the report.", false},
	})
}

func TestDetectPaddedVerb(t *testing.T) {
	runHits(t, "padded-verb", DetectPaddedVerb, []hitCase{
		{"allows you to", "The flag allows you to skip the check.", true},
		{"allows users to", "The plugin allows users to pin a version.", true},
		{"is able to", "The parser is able to recover from a bad header.", true},
		{"it is possible to", "It is possible to run both layers at once.", true},
		{"can be used to", "The API can be used to fetch a report.", true},
		{"has the ability to", "The tool has the ability to rewrite prose.", true},
		{"wrapped across a line", "The flag allows\nyou to skip the check.", true},
		{"lets you is the fix, not the fault", "The flag lets you skip the check.", false},
		{"plain modal", "You can run both layers at once.", false},
	})
}

func TestDetectPaddedVerbSuggestion(t *testing.T) {
	v := DetectPaddedVerb("The flag allows you to skip the check.")
	if len(v) != 1 || v[0].SuggestedChange != "lets you" {
		t.Fatalf("got %+v, want one violation suggesting %q", v, "lets you")
	}
}

func TestDetectMissingHyphen(t *testing.T) {
	runHits(t, "missing-hyphen", DetectMissingHyphen, []hitCase{
		{"command line tool", "The command line tool prints JSON.", true},
		{"open source project", "An open source project needs a license.", true},
		{"real time dashboard", "A real time dashboard shows the queue.", true},
		{"end to end suite", "The end to end suite runs nightly.", true},
		{"read only mount", "Use a read only mount for the cache.", true},
		{"possessive determiner", "Our command line tool prints JSON.", true},
		{"quantifier determiner", "Every command line tool needs docs.", true},
		{"plural possessive", "Their open source project needs a license.", true},
		{"predicate position", "The tool is open source.", false},
		{"modal follows", "A third party may audit the code.", false},
		{"preposition follows", "Read the command line of the process.", false},
		{"already hyphenated", "The command-line tool prints JSON.", false},
		{"no determiner", "Run it from command line tools.", false},
		{"lexical verb follows", "A command line goes here.", false},
		{"proper noun stays open", "The build rejects the Command Line Tools, so install Xcode.", false},
		{"title case only when every word is capitalised", "The Command line tool prints JSON.", true},
	})
}

// A phrasal-verb noun is already a noun once a determiner introduces it, so it
// earns its hyphen without a following noun. Only an object following the
// second word shows that word is really a preposition.
func TestDetectMissingHyphenPhrasalNouns(t *testing.T) {
	runHits(t, "missing-hyphen", DetectMissingHyphen, []hitCase{
		{"check in before noon", "Complete the check in before noon.", true},
		{"follow up after the call", "Ship the follow up after the call.", true},
		{"roll out starts", "The roll out starts Monday.", true},
		{"work around for the bug", "The team wrote a work around for the bug.", true},
		{"trade off between", "We need a trade off between speed and memory.", true},
		{"ends the sentence", "Complete the check in.", true},
		{"drop down menu", "A drop down menu appears.", true},
		{"preposition with an object", "Deposit the check in the bank.", false},
		{"work around the house", "The work around the house is done.", false},
		{"drop down the shaft", "The drop down the shaft was measured.", false},
		{"already hyphenated", "Complete the check-in before noon.", false},
	})
}

// A determiner after a phrasal-verb noun heads a reduced relative clause
// ("the roll out [that] your team scheduled"), not a prepositional phrase, so
// only the locative compounds — whose second word really can take an object —
// stay silent on it.
func TestDetectMissingHyphenReducedRelative(t *testing.T) {
	runHits(t, "missing-hyphen", DetectMissingHyphen, []hitCase{
		{"roll out", "The roll out your team scheduled needs QA.", true},
		{"trade off", "We accepted the trade off our team proposed.", true},
		{"follow up", "Ship the follow up your manager requested.", true},
		{"fall back", "The fall back your config names is stale.", true},
		{"opt in", "Review the opt in your form collects.", true},
		{"opt out", "Review the opt out your form collects.", true},
		{"check in stays gated", "Complete the check in your team scheduled.", false},
		{"work around stays gated", "Fix the work around your team wrote.", false},
		{"drop down stays gated", "Use the drop down your designer specified.", false},
	})
}

func TestDetectMissingHyphenSuggestion(t *testing.T) {
	v := DetectMissingHyphen("The command line tool prints JSON.")
	if len(v) != 1 {
		t.Fatalf("got %d violations, want 1", len(v))
	}
	if v[0].MatchedText != "command line" || v[0].SuggestedChange != "command-line" {
		t.Fatalf("got %q -> %q, want %q -> %q",
			v[0].MatchedText, v[0].SuggestedChange, "command line", "command-line")
	}
}

func TestDetectExpletiveOpener(t *testing.T) {
	runHits(t, "expletive-opener", DetectExpletiveOpener, []hitCase{
		{"there is", "There is a flag that controls the layer.", true},
		{"there are", "There are two ways to run the check.", true},
		{"there was", "There was a bug in the parser.", true},
		{"mid-paragraph sentence", "The layer is on. There are two ways to run the check.", true},
		{"list marker stripped", "- There is a flag that controls the layer.", true},
		{"blockquote marker stripped", "> There was a bug in the parser.", true},
		{"heading marker stripped", "## There are two ways to run the check", true},
		{"negation carve-out", "There are no guarantees.", false},
		{"negation nothing", "There is nothing to fix.", false},
		{"negation few", "There are few options left.", false},
		{"emphasised negation", "There are *no* guarantees.", false},
		{"enumerating colon", "There are three modes:", false},
		{"not sentence-initial", "The flag is there and it is set.", false},
	})
}

func TestDetectNominalization(t *testing.T) {
	runHits(t, "nominalization", DetectNominalization, []hitCase{
		{"make a decision", "We need to make a decision about the format.", true},
		{"perform an analysis", "The team will perform an analysis of the logs.", true},
		{"reach a conclusion", "The reviewers reach a conclusion after two passes.", true},
		{"has an impact on", "The change has an impact on latency.", true},
		{"make use of", "The script makes use of the cache.", true},
		{"plain verb", "We decided on the format.", false},
		{"documentation is not a nominalization", "The documentation covers the implementation and the configuration.", false},
		{"argument and environment", "The argument changes the environment.", false},
		{"consideration belongs to false-conclusion", "We gave consideration to the request.", false},
		{"taking into consideration", "Taking everything into consideration, we shipped.", false},
	})
}

func TestProseWordCount(t *testing.T) {
	cases := []struct {
		name string
		text string
		want int
	}{
		{"plain", "one two three", 3},
		{"parenthetical is one token", "one (two three four five) six", 3},
		{"quoted is one token", `one "two three four five" six`, 3},
		{"curly quoted is one token", "one “two three four” six", 3},
		{"attached parenthetical does not split", "call(a b c) again", 2},
		{"unbalanced paren left alone", "one (two three", 3},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := proseWordCount(c.text); got != c.want {
				t.Fatalf("proseWordCount(%q) = %d, want %d", c.text, got, c.want)
			}
		})
	}
}

func TestProseWordCountNeverExceedsFields(t *testing.T) {
	corpus := []string{
		longSentence,
		`one "two three" (four five) six`,
		"call(a b c) again \"x y\"(z)",
		"(leading) trailing (a)(b)(c)",
		`"" () a`,
		"no punctuation at all here",
		"“smart quotes” and (parens) mixed",
	}
	for _, s := range corpus {
		if got, upper := proseWordCount(s), len(strings.Fields(s)); got > upper {
			t.Fatalf("proseWordCount(%q) = %d > len(Fields) = %d", s, got, upper)
		}
	}
}

func TestMergeAbbrev(t *testing.T) {
	cases := []struct {
		name string
		text string
		want int
	}{
		{"e.g.", "Run it on a file, e.g. README.md, and stop. Then check.", 2},
		{"i.e.", "Use the base layer, i.e. the clarity rules, first. Then the slop layer.", 2},
		{"Fig.", "See Fig. 3 for the pipeline. The rest follows.", 2},
		{"initials", "The author is J. R. R. Tolkien. The book is long.", 2},
		{"no abbreviation", "One runs. Two runs.", 2},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := mergeAbbrev(splitSentences(c.text))
			if len(got) != c.want {
				t.Fatalf("mergeAbbrev(%q) = %d sentences %q, want %d", c.text, len(got), got, c.want)
			}
			if strings.Join(got, "") != c.text {
				t.Fatalf("merge lost bytes: %q != %q", strings.Join(got, ""), c.text)
			}
		})
	}
}

func TestRunBaseWiresEveryRule(t *testing.T) {
	doc := strings.Join([]string{
		longSentence,
		"One runs. Two runs. Three runs. Four runs. Five runs. Six runs. Seven runs.",
		"The report is generated by the analyzer.",
		"The flag allows you to skip the check.",
		"The command line tool prints JSON.",
		"There is a flag that controls the layer.",
		"The script makes use of the cache.",
		"The change is not uncommon.",
	}, "\n\n")
	want := []string{
		"long-sentence", "long-paragraph", "passive-voice", "padded-verb",
		"missing-hyphen", "expletive-opener", "nominalization", "elevated-register",
	}
	got := RunBase(doc)
	for _, id := range want {
		if !hasRule(got, id) {
			t.Fatalf("RunBase did not emit %s\ngot: %+v", id, got)
		}
	}
}

// RunBase is a sibling of RunClient, never a superset: the slop layer must not
// leak base-layer rule IDs, which is what makes --standard=slop reproducible.
func TestRunClientEmitsNoBaseRules(t *testing.T) {
	doc := longSentence + "\n\nThe report is generated by the analyzer. " +
		"The flag allows you to skip the check. The command line tool prints JSON. " +
		"There is a flag that controls the layer."
	for _, id := range []string{
		"long-sentence", "long-paragraph", "passive-voice", "padded-verb",
		"missing-hyphen", "expletive-opener", "nominalization",
	} {
		if hasRule(RunClient(doc), id) {
			t.Fatalf("RunClient emitted base-layer rule %s", id)
		}
	}
}

func TestBaseSpansIndexTheSource(t *testing.T) {
	doc := "Intro line.\n\n" + longSentence + "\n\nThe report is generated by the analyzer.\n\n" +
		"The command line tool prints JSON. There is a flag that controls the layer.\n\n" +
		"The script makes use of the cache and the flag allows you to skip the check.\n"
	for _, v := range RunBase(doc) {
		if v.StartIndex < 0 || v.EndIndex > len(doc) || v.StartIndex >= v.EndIndex {
			t.Fatalf("%s: span [%d,%d) out of range for %d bytes", v.RuleID, v.StartIndex, v.EndIndex, len(doc))
		}
		if got := doc[v.StartIndex:v.EndIndex]; got != v.MatchedText {
			t.Fatalf("%s: MatchedText %q does not match source slice %q", v.RuleID, v.MatchedText, got)
		}
	}
}

func TestBaseDetectorsOnEmptyInput(t *testing.T) {
	for _, d := range []func(string) []types.Violation{
		DetectLongSentence, DetectLongParagraph, DetectPassiveVoice, DetectPaddedVerb,
		DetectMissingHyphen, DetectExpletiveOpener, DetectNominalization, DetectPlainWord,
	} {
		if got := d(""); len(got) != 0 {
			t.Fatalf("empty input produced %+v", got)
		}
	}
}

// abbrevDoc is the shape that made mergeAbbrev quadratic: every sentence ends
// at an abbreviation, so the whole document merges into one group.
func abbrevDoc(n int) string { return strings.Repeat("Run it on a file, e.g. ", n) }

func BenchmarkDetectLongSentenceAbbrev(b *testing.B) {
	for _, n := range []int{500, 1000, 2000, 4000} {
		doc := abbrevDoc(n)
		b.Run(itoa(n), func(b *testing.B) {
			b.SetBytes(int64(len(doc)))
			for i := 0; i < b.N; i++ {
				DetectLongSentence(doc)
			}
		})
	}
}
