package detectors

import "github.com/yasyf/slop-cop/internal/types"

// RunGoogle executes every google-layer (style guide) detector over text and
// returns a merged, deduplicated slice of violations. It is a sibling of
// [RunClient] and [RunBase], never a superset: the three layers are selected
// independently, so `--standard=slop` reproduces the pre-base-layer output
// exactly.
func RunGoogle(text string) []types.Violation {
	detectors := []func(string) []types.Violation{
		DetectGoogleAbbreviationBeforeExpansion,
		DetectGoogleAcronymPeriods,
		DetectGoogleAdjacentNumerals,
		DetectGoogleAllCapsEmphasis,
		DetectGoogleAlternativeInStep,
		DetectGoogleAmPmFormat,
		DetectGoogleAmbiguousNumericDate,
		DetectGoogleAmbiguousRepeatedLinkText,
		DetectGoogleAmbiguousSectionReference,
		DetectGoogleAmpersandConjunction,
		DetectGoogleAndOrSlash,
		DetectGoogleAnthropomorphism,
		DetectGoogleApostrophePlural,
		DetectGoogleBrandNameAsVerb,
		DetectGoogleBrandNameCasing,
		DetectGoogleCheckboxVerb,
		DetectGoogleCompoundSpelling,
		DetectGoogleCompoundSubjectAgreement,
		DetectGoogleConjunctiveAdverbPunctuation,
		DetectGoogleCurrencyFormat,
		DetectGoogleDateAbbreviationConsistency,
		DetectGoogleDirectionalReference,
		DetectGoogleDocSelfReference,
		DetectGoogleDoubleNegative,
		DetectGoogleDroppedArticle,
		DetectGoogleDuplicateLinkTarget,
		DetectGoogleEllipsisInProse,
		DetectGoogleExclamationPoint,
		DetectGoogleExpansionNumberMismatch,
		DetectGoogleExtensionAsFileType,
		DetectGoogleFootnoteUsage,
		DetectGoogleFutureFeaturePromise,
		DetectGoogleFutureTenseBehavior,
		DetectGoogleGerundHeading,
		DetectGoogleHeadingLevelSkip,
		DetectGoogleHeadingRepeatsTitle,
		DetectGoogleHeadingSentenceCase,
		DetectGoogleHeadingTerminalPeriod,
		DetectGoogleHyphenatedWordCapitalization,
		DetectGoogleIdiomColloquialism,
		DetectGoogleImpersonalRecommendation,
		DetectGoogleImpreciseUINoun,
		DetectGoogleInconsistentListPunctuation,
		DetectGoogleIndefiniteArticleAbbreviation,
		DetectGoogleInflectedCodeElement,
		DetectGoogleInternetSlang,
		DetectGoogleIntroCommaMissing,
		DetectGoogleIntroRestatesHeading,
		DetectGoogleKSuffixThousands,
		DetectGoogleKeyboardShortcutInstruction,
		DetectGoogleLatinAbbreviation,
		DetectGoogleLeadingZeroDecimal,
		DetectGoogleLinkInHeading,
		DetectGoogleListItemSentenceCase,
		DetectGoogleLongParenthetical,
		DetectGoogleLyAdverbHyphen,
		DetectGoogleMissingTerminalPeriod,
		DetectGoogleMonthYearComma,
		DetectGoogleMultiActionStep,
		DetectGoogleMultiwordForSingleWord,
		DetectGoogleNeitherNorPairing,
		DetectGoogleNonstandardContraction,
		DetectGoogleNoteAsCrossReference,
		DetectGoogleNoteCarriesRequiredInfo,
		DetectGoogleNoticePileup,
		DetectGoogleNoticeSeverityMismatch,
		DetectGoogleNumberUnitModifierHyphen,
		DetectGoogleNumberedHeading,
		DetectGoogleNumeralUnderTen,
		DetectGoogleOneOrMoreAgreement,
		DetectGoogleOptionalPluralParens,
		DetectGoogleOutputIntroPhrase,
		DetectGoogleOverExplainedAbbreviation,
		DetectGoogleOverlongCompoundModifier,
		DetectGoogleOverlongLinkText,
		DetectGoogleParentheticalAcronymPossessive,
		DetectGoogleParentheticalPeriodPlacement,
		DetectGooglePassiveByAgent,
		DetectGooglePerOutsideRates,
		DetectGooglePercentFormat,
		DetectGooglePiedPiping,
		DetectGooglePlaceholderPhrase,
		DetectGooglePlainWordSwap,
		DetectGooglePleaseInInstructions,
		DetectGooglePluralPossessiveApostrophe,
		DetectGooglePluralizedUnitAbbreviation,
		DetectGooglePostColonCapitalization,
		DetectGooglePostVerbCompoundHyphen,
		DetectGoogleProductNameAbbreviation,
		DetectGooglePunctuationInsideLink,
		DetectGoogleQuotePeriodPlacement,
		DetectGoogleQuotesAroundCodeSpan,
		DetectGoogleRangeWordDashMix,
		DetectGoogleRateSlash,
		DetectGoogleReaderAddressPerson,
		DetectGoogleRunTheFollowingCommand,
		DetectGoogleSentenceInitialNumeral,
		DetectGoogleSerialComma,
		DetectGoogleSibilantAbbreviationPlural,
		DetectGoogleSingleItemList,
		DetectGoogleSingleQuotesInProse,
		DetectGoogleSingleUseAbbreviation,
		DetectGoogleSpacedHyphen,
		DetectGoogleSpelledOutOrdinals,
		DetectGoogleSpelledOutShorthand,
		DetectGoogleStepLacksImperative,
		DetectGoogleSuccessNoticeInStaticDoc,
		DetectGoogleSuperlativeProductClaim,
		DetectGoogleTermIntroductionFormatting,
		DetectGoogleThatWhichClause,
		DetectGoogleTimeBoundQualifier,
		DetectGoogleToggleAsVerb,
		DetectGoogleTrailingForExampleComma,
		DetectGoogleTrivializingDifficulty,
		DetectGoogleTwoDigitYear,
		DetectGoogleUIDeviceNaming,
		DetectGoogleUILabelDecoration,
		DetectGoogleUILabelEllipsis,
		DetectGoogleUIPreposition,
		DetectGoogleUndefinedAbbreviation,
		DetectGoogleUnderlineNonLink,
		DetectGoogleUnderspecifiedTerm,
		DetectGoogleUnexplainedLinkBehavior,
		DetectGoogleUnfencedCommandLine,
		DetectGoogleUnformattedCodeIdentifier,
		DetectGoogleUnitNumberAgreement,
		DetectGoogleUnitSpaceMissing,
		DetectGoogleUnqualifiedCodeElement,
		DetectGoogleUppercaseUILabel,
		DetectGoogleURLTerminalPeriod,
		DetectGoogleUsEnglishSpelling,
		DetectGoogleVagueLinkText,
		DetectGoogleVerbNounCompound,
		DetectGoogleVersionRangeComparator,
		DetectGoogleVisualAppearanceReference,
		DetectGoogleWordFractionHyphen,
	}
	all := make([]types.Violation, 0, len(detectors))
	for _, d := range detectors {
		all = append(all, d(text)...)
	}
	return Deduplicate(all)
}
