package detectors

// plainSub is a from→to substitution: the flagged text and the plain word or
// phrase that replaces it.
type plainSub struct{ from, to string }

// plainWordSubs extends the elevated-register vocabulary with words the
// upstream list has no stem for. Inflections of an upstream stem are
// deliberately absent (utilizes, commenced, ascertained, crafted…): the
// upstream detector owns those families. So are words with ordinary technical
// senses — reside, personnel, implement, execute, abort, terminate, invoke,
// instantiate, deprecate, serialize — and legalese, whose measured hits were
// almost entirely quoted MIT and code-of-conduct boilerplate.
var plainWordSubs = []plainSub{
	{"accomplish", "do"},
	{"accomplishes", "does"},
	{"accomplished", "did"},
	{"accomplishing", "doing"},
	{"attain", "reach"},
	{"attains", "reaches"},
	{"attained", "reached"},
	{"attaining", "reaching"},
	{"cease", "stop"},
	{"ceases", "stops"},
	{"ceased", "stopped"},
	{"ceasing", "stopping"},
	{"conceal", "hide"},
	{"conceals", "hides"},
	{"concealed", "hid"},
	{"concealing", "hiding"},
	{"delineate", "outline"},
	{"delineates", "outlines"},
	{"delineated", "outlined"},
	{"delineating", "outlining"},
	{"disseminate", "share"},
	{"disseminates", "shares"},
	{"disseminated", "shared"},
	{"disseminating", "sharing"},
	{"encompass", "cover"},
	{"encompasses", "covers"},
	{"encompassed", "covered"},
	{"encompassing", "covering"},
	{"entail", "involve"},
	{"entails", "involves"},
	{"entailed", "involved"},
	{"entailing", "involving"},
	{"expedite", "speed up"},
	{"expedites", "speeds up"},
	{"expedited", "sped up"},
	{"expediting", "speeding up"},
	{"inquire", "ask"},
	{"inquires", "asks"},
	{"inquired", "asked"},
	{"inquiring", "asking"},
	{"possess", "have"},
	{"possesses", "has"},
	{"possessed", "had"},
	{"possessing", "having"},
	{"preclude", "prevent"},
	{"precludes", "prevents"},
	{"precluded", "prevented"},
	{"precluding", "preventing"},
	{"procure", "get"},
	{"procures", "gets"},
	{"procured", "got"},
	{"procuring", "getting"},
	{"assist", "help"},
	{"assists", "helps"},
	{"assisted", "helped"},
	{"assisting", "helping"},
	{"operationalize", "put into practice"},
	{"operationalizes", "puts into practice"},
	{"operationalized", "put into practice"},
	{"operationalizing", "putting into practice"},
	{"incentivize", "encourage"},
	{"incentivizes", "encourages"},
	{"incentivized", "encouraged"},
	{"incentivizing", "encouraging"},
	{"whilst", "while"},
	{"amongst", "among"},
	{"albeit", "though"},
	{"myriad", "many"},
	{"plethora", "many"},
	{"bespoke", "custom"},
	{"seamless", "smooth"},
	{"seamlessly", "smoothly"},
	{"meticulous", "careful"},
	{"meticulously", "carefully"},
	{"paramount", "most important"},
	{"subsequently", "then"},
	{"approximately", "about"},
	{"approximate", "rough"},
	{"evident", "clear"},
	{"methodology", "method"},
	{"methodologies", "methods"},
	{"nomenclature", "names"},
	{"verbiage", "wording"},
	{"learnings", "lessons"},
	{"aforementioned", "this"},
	{"optimal", "best"},
	{"optimally", "best"},
	{"numerous", "many"},
	{"multitude", "many"},
	{"requisite", "needed"},
	{"substantial", "large"},
	{"substantially", "much"},
	{"considerable", "large"},
	{"considerably", "much"},
	{"rudimentary", "basic"},
	{"pertinent", "relevant"},
	{"salient", "key"},
	{"granular", "detailed"},
	{"granularity", "detail"},
	{"performant", "fast"},
	{"takeaway", "lesson"},
	{"takeaways", "lessons"},
	{"impactful", "effective"},
}

// plainPhraseSubs holds the wordy phrases and redundant pairs. "the fact that"
// and "not unlike" are absent: the first overlaps "due to the fact that", the
// second contains "unlike", an unnecessary-contrast entry.
var plainPhraseSubs = []plainSub{
	{"in order to", "to"},
	{"prior to", "before"},
	{"subsequent to", "after"},
	{"due to the fact that", "because"},
	{"despite the fact that", "although"},
	{"in the event that", "if"},
	{"at this point in time", "now"},
	{"at the present time", "now"},
	{"in the near future", "soon"},
	{"a large number of", "many"},
	{"a number of", "some"},
	{"the majority of", "most"},
	{"for the purpose of", "to"},
	{"with the exception of", "except"},
	{"in excess of", "more than"},
	{"with regard to", "about"},
	{"with reference to", "about"},
	{"in accordance with", "per"},
	{"in an effort to", "to"},
	{"attempt to", "try to"},
	{"by means of", "by"},
	{"in spite of", "despite"},
	{"in the absence of", "without"},
	{"in conjunction with", "with"},
	{"in the vicinity of", "near"},
	{"on a regular basis", "regularly"},
	{"for the most part", "mostly"},
	{"in many cases", "often"},
	{"in most cases", "usually"},
	{"in some cases", "sometimes"},
	{"in the course of", "during"},
	{"period of time", "time"},
	{"whether or not", "whether"},
	{"is capable of", "can"},
	{"are capable of", "can"},
	{"each and every", "every"},
	{"first and foremost", "first"},
	{"exact same", "same"},
	{"revert back", "revert"},
	{"end result", "result"},
	{"past history", "history"},
	{"various different", "various"},
	{"not uncommon", "common"},
}
